spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Brayan-22/ud-central-configuration
          default-label: dev
      profile: default
  config:
    activate:
      on-profile: dev
server:
  port: 9196
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${HOSTNAME:localhost}
management:
  endpoints:
    web:
      exposure:
        include: health