spring:
  application:
    name: apigateway
  config:
    import: optional:configserver:http://localhost:9196
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${HOSTNAME:localhost}
server:
  port: 8080