spring:
  application:
    name: ${APP_NAME:MACARENA-SERVICE}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5433/macarena}
    username: ${DB_USER:macarena}
    password: ${DB_PASS:macarena}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9196}
  webflux:
    base-path: /${BASE_PATH:macarena}

  cloud:
    function:
      definition: profesorSupplier;pregradoSupplier;centralEventConsumer
    stream:
      bindings:
        profesorSupplier-out-0:
          destination: profesor-event
          content-type: application/json
        centralEventConsumer-in-0:
          destination: central-response
          content-type: application/json
        pregradoSupplier-out-0:
          destination: pregrado-event
          content-type: application/json
  kafka:
    bootstrap-servers: ${KAFKA_URL:http://localhost:29092}
server:
  port: ${PORT:8091}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME:localhost}
springdoc:
  open-api:
    service:
      title: ${APP_NAME}
      version: 1.0.0
      url: /${BASE_PATH}
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html