spring:
  application:
    name: @project.artifactId@
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: ${HOSTNAME:localhost}
  server:
    peer-node-read-timeout-ms: 2000
    peer-node-connect-timeout-ms: 2000
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: ${EUREKA_PORT}