spring:
  application:
    name: discovery-service
eureka:
  server:
    peer-node-connection-idle-timeout-seconds: 30
    peer-node-connect-timeout-ms: 20000
    peer-node-read-timeout-ms: 20000
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: ${HOSTNAME:localhost}
server:
  port: 8761