services:
  chapinero-service:
    image: brayan22/central-ud:latest
    container_name: chapinero-ud
    expose:
      - "8090"
    environment:
      DB_URL: jdbc:postgresql://chapinero-db:5432/chapinero
      DB_USER: chapinero
      DB_PASS: chapinero
      EUREKA_URL: http://discovery-ud:8761/eureka/
      CONFIG_SERVER_URL: http://config-ud:9196
      HOSTNAME: chapinero-ud
      KAFKA_URL: kafka:9092
    hostname: chapinero-ud
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-ud
      - ud-distribuida
  macarena-service:
    image: brayan22/sede-ud:latest
    container_name: macarena-ud
    expose:
      - "8091"
    environment:
      APP_NAME: macarena-service
      DB_URL: jdbc:postgresql://macarena-db:5432/macarena
      DB_USER: macarena
      DB_PASS: macarena
      EUREKA_URL: http://discovery-ud:8761/eureka/
      CONFIG_SERVER_URL: http://config-ud:9196
      HOSTNAME: macarena-ud
      PORT: 8091
      BASE_PATH: macarena
      KAFKA_URL: kafka:9092
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-ud
      - ud-distribuida
  cbolivar-service:
    image: brayan22/sede-ud:latest
    container_name: cbolivar-ud
    expose:
      - "8092"
    environment:
      APP_NAME: cbolivar-service
      DB_URL: jdbc:postgresql://cbolivar-db:5432/cbolivar
      DB_USER: cbolivar
      DB_PASS: cbolivar
      EUREKA_URL: http://discovery-ud:8761/eureka/
      CONFIG_SERVER_URL: http://config-ud:9196
      HOSTNAME: cbolivar-ud
      PORT: 8092
      BASE_PATH: cbolivar
      KAFKA_URL: kafka:9092
    networks:
      - app-ud
      - ud-distribuida
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  app-ud:
    external: true
  ud-distribuida:
    external: true